### Create job
POST http://localhost:3001/jobs
Content-Type: application/json

{
    "job":{
        "title": "Full Stack Developer",
        "locationCom": "London Bay, ON",
        "company": "Dreamland VR",
        "salary":"45000 - 70000"
    }
}

### Update job
PUT http://localhost:3001/jobs/5f53ed3eeb37d114c415188f
Content-Type: application/json

{
    "job":{
        "title": "Full Stack Developer",
        "locationCom": "London Bay, ON",
        "company": "Dreamland VR",
        "salary":"$45,000 - $70,000 a year"
    }
}

### Retrieve job
GET http://localhost:3001/jobs?q=full+stack+developer&&start=10

### Delete job
DELETE http://localhost:3001/jobs/5f5230091f4e180e56db1a99
